import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import quickAnswerRoutes from "./quickAnswerRoutes";
import apiRoutes from "./apiRoutes";
import tagRoutes from "./tagRoutes";
import contactListRoutes from "./contactListRoutes";
import dialogRoutes from "./dialogRoutes";
import campaignRoutes from "./campaignRoutes";
import dashboardRoutes from "./dashboardRoutes";
import integrationRoutes from "./integrationRoutes";
import webhookRoutes from "./webhookRoutes";
import informativeRoutes from "./informativeRoutes";
import kanbanRoutes from "./kanbanRoutes";
import taskRoutes from "./taskRoutes";
import fileListRoutes from "./fileListRoutes";
import scheduleRoutes from "./scheduleRoutes";
import flowRoutes from "./flowRoutes";
import flowExecutionRoutes from "./flowExecutionRoutes";
import adminRoutes from "./adminRoutes";
import openAIRoutes from "./openAIRoutes";
import aiRoutes from "./aiRoutes";
import agendaRoutes from "./agendaRoutes";
import sdrAgentRoutes from "./sdrAgentRoutes";

const routes = Router();

routes.use(userRoutes);
routes.use("/auth", authRoutes);
routes.use(settingRoutes);
routes.use(dashboardRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(quickAnswerRoutes);
routes.use(tagRoutes);
routes.use(contactListRoutes);
routes.use(dialogRoutes);
routes.use(campaignRoutes);
routes.use(integrationRoutes);
routes.use(webhookRoutes);
routes.use(informativeRoutes);
routes.use(kanbanRoutes);
routes.use(taskRoutes);
routes.use(fileListRoutes);
routes.use(scheduleRoutes);
routes.use(flowRoutes);
routes.use(flowExecutionRoutes);
routes.use(adminRoutes);
routes.use(openAIRoutes);
routes.use(aiRoutes);
routes.use(agendaRoutes);
routes.use(sdrAgentRoutes);
routes.use("/api/messages", apiRoutes);

export default routes;
